//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsWorking { get; set; }
        public string WorkingPlace { get; set; }
        public bool IsStudying { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<int> ConfessionFather { get; set; }
        public Nullable<int> ServantID { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual Father Father { get; set; }
        public virtual Servant Servant { get; set; }
    }
}
