//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Family()
        {
            this.FamilyServants = new HashSet<FamilyServant>();
            this.FamilyVisits = new HashSet<FamilyVisit>();
            this.ServiceActions = new HashSet<ServiceAction>();
            this.Children = new HashSet<Child>();
        }
    
        public int ID { get; set; }
        public string FamilyCode { get; set; }
        public string Address { get; set; }
        public Nullable<int> ServantID { get; set; }
        public Nullable<int> NoOfChildren { get; set; }
        public Nullable<int> FatherID { get; set; }
        public Nullable<int> MotherID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MissingPriestID { get; set; }
        public Nullable<int> EvaluationLevelID { get; set; }
    
        public virtual EvaluationLevel EvaluationLevel { get; set; }
        public virtual Father Father { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Servant Servant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyServant> FamilyServants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyVisit> FamilyVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceAction> ServiceActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children { get; set; }
    }
}
