//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalContract
    {
        public int ID { get; set; }
        public Nullable<int> MedicalServiceID { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual MedicalService MedicalService { get; set; }
    }
}
