//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Families = new HashSet<Family>();
            this.Families1 = new HashSet<Family>();
            this.ServiceActions = new HashSet<ServiceAction>();
        }
    
        public int ID { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public string WorkingPlace { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ServantID { get; set; }
        public Nullable<int> ConfessionFather { get; set; }
        public Nullable<bool> IsWidow { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Notes { get; set; }
        public string NationalID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string OtherIncome { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families1 { get; set; }
        public virtual Father Father { get; set; }
        public virtual Servant Servant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceAction> ServiceActions { get; set; }
    }
}
