//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Web.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurchDataSheet
    {
        public int ID { get; set; }
        public string HusbandName { get; set; }
        public string HusbandMobile { get; set; }
        public string WifeName { get; set; }
        public string WifeMobile { get; set; }
        public string Address { get; set; }
    }
}
