//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Web.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServantService
    {
        public int ID { get; set; }
        public int ChurchServiceID { get; set; }
        public int ChurchServantID { get; set; }
    
        public virtual ChurchServant ChurchServant { get; set; }
        public virtual ChurchService ChurchService { get; set; }
    }
}
