//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Web.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShroukFamily
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public Nullable<int> FamilyCode { get; set; }
    }
}
