//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraamFamily.Web.Entities.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaintAbraamEntities : DbContext
    {
        public SaintAbraamEntities()
            : base("name=SaintAbraamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Clinic> Clinics { get; set; }
        public virtual DbSet<EvaluationLevel> EvaluationLevels { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<FamilyServant> FamilyServants { get; set; }
        public virtual DbSet<FamilyVisit> FamilyVisits { get; set; }
        public virtual DbSet<Father> Fathers { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<MedicalContract> MedicalContracts { get; set; }
        public virtual DbSet<MedicalService> MedicalServices { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Servant> Servants { get; set; }
        public virtual DbSet<ServiceAction> ServiceActions { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CovidReservation> CovidReservations { get; set; }
        public virtual DbSet<ChurchServant> ChurchServants { get; set; }
        public virtual DbSet<ChurchService> ChurchServices { get; set; }
        public virtual DbSet<ServantService> ServantServices { get; set; }
    }
}
